### Task 1: Import NumPy


In [3]:
import numpy as np
print(np.__version__)

2.3.5


### Task2: Create the Sensor Array

In [6]:
temps = np.array([57, 55, 54, 53, 53, 54, 56, 60,
65, 70, 74, 78, 81, 83, 84, 84,
82, 79, 74, 70, 66, 63, 61, 59])
print(temps)
print(temps.shape)
print(temps.dtype)

[57 55 54 53 53 54 56 60 65 70 74 78 81 83 84 84 82 79 74 70 66 63 61 59]
(24,)
int64


### Task 3: Convert to Celsius

In [7]:
temps_c = (temps - 32) * 5 / 9

print(temps_c)

[13.88888889 12.77777778 12.22222222 11.66666667 11.66666667 12.22222222
 13.33333333 15.55555556 18.33333333 21.11111111 23.33333333 25.55555556
 27.22222222 28.33333333 28.88888889 28.88888889 27.77777778 26.11111111
 23.33333333 21.11111111 18.88888889 17.22222222 16.11111111 15.        ]


### Task 4: Summarize the Day

In [13]:
sum = np.sum(temps)
Mean = np.mean(temps)
Min = np.min(temps)
Max = np.max(temps)
Median = np.median(temps)


print("Sum:", sum)
print("Mean:", Mean)
print("Min:", Min)
print("Max:", Max)
print("Median:", Median)

Sum: 1615
Mean: 67.29166666666667
Min: 53
Max: 84
Median: 65.5


### Task 5: What was the warmest hour?

In [17]:
print(f"2:00 PM temperature:{temps[14]}")
print(f"11:00 PM temperature: {temps[-1]}")

2:00 PM temperature:84
11:00 PM temperature: 59


### Task 6: Slice out the afternoon

In [55]:
temps

array([57, 55, 54, 53, 53, 54, 56, 60, 65, 70, 74, 78, 81, 83, 84, 84, 82,
       79, 74, 70, 66, 63, 61, 59])

In [18]:
afternoon = temps[12:18]
print(afternoon)
print(afternoon.shape)

[81 83 84 84 82 79]
(6,)


### Task 7: Flag the hot hours

In [56]:
temps > 80

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False])

In [20]:
hot_hours = temps[(temps>80)]
print(hot_hours)
print(len(hot_hours))

[81 83 84 84 82]
5


### Task 8: Build a 2D Sensor Table

In [23]:
sensor_grid = np.array([[81, 83, 84, 84, 82, 79], [78, 80, 82, 83, 81, 77], [83, 85, 87, 88, 86, 82]])
print(sensor_grid)
print(sensor_grid.shape)

[[81 83 84 84 82 79]
 [78 80 82 83 81 77]
 [83 85 87 88 86 82]]
(3, 6)


### Task 9: Read one sensor and one hour

In [30]:
print(sensor_grid[2,2])
print(sensor_grid[1,:])
print(sensor_grid[:,0])

87
[78 80 82 83 81 77]
[81 78 83]


### Task 10: Mean temperature per sensor

In [48]:
print(f"Sensor 1 mean: {np.mean(sensor_grid[0,:])} F")
print(f"Sensor 2 mean: {np.mean(sensor_grid[1,:])} F")
print(f"Sensor 3 mean: {np.mean(sensor_grid[2,:])} F")

print(sensor_grid)
print(sensor_grid[:,3])

Sensor 1 mean: 82.16666666666667 F
Sensor 2 mean: 80.16666666666667 F
Sensor 3 mean: 85.16666666666667 F
[[81 83 84 84 82 79]
 [78 80 82 83 81 77]
 [83 85 87 88 86 82]]
[84 83 88]


### AT Task 11: Temperature range per hour

In [53]:
hour_1 = np.max(sensor_grid[:,0]) - np.min(sensor_grid[:,0])
hour_2 = np.max(sensor_grid[:,1]) - np.min(sensor_grid[:,1])
hour_3 = np.max(sensor_grid[:,2]) - np.min(sensor_grid[:,2])
hour_4 = np.max(sensor_grid[:,3]) - np.min(sensor_grid[:,3])
hour_5 = np.max(sensor_grid[:,4]) - np.min(sensor_grid[:,4])
hour_6 = np.max(sensor_grid[:,5]) - np.min(sensor_grid[:,5])
print(hour_1)
print(hour_2)
print(hour_3)
print(hour_4)
print(hour_5)
print(hour_6)

hourly_range = [hour_1, hour_2, hour_3, hour_4, hour_5, hour_6]


x = np.array(hourly_range)
print(x)



5
5
5
5
5
5
[5 5 5 5 5 5]


### Task 12: Normalize the afternoon readings

In [57]:
afternoon_v = np.array(afternoon)
# calculate min
afternoon_min = np.min(afternoon)
#calculate max
afternoon_max = np.max(afternoon)
#create new array using formulas above
afternoon_norm = (afternoon_v - afternoon_min) / (afternoon_max - afternoon_min)
print(afternoon_norm)

[0.4 0.8 1.  1.  0.6 0. ]
